spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:${DATASOURCE_DBTYPE:mysql}://${DATASOURCE_HOST:chauncy}:${DATASOURCE_PORT:3358}/tickets?characterEncoding=UTF-8&useUnicode=true&useSSL=false
        username: ${DATASOURCE_USERNAME:root}
        password: ${DATASOURCE_PASSWORD:root}
        names: odps
        odps:
            type: com.alibaba.druid.pool.DruidDataSource
            driver-class-name: com.aliyun.odps.jdbc.OdpsDriver
            url: jdbc:odps:XX/api?project=vanchan
            username: XX
            password: XX
        dynamic:
            primary: master #设置默认的数据源或者数据源组,默认值即为master
            strict: true #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
            datasource:
                master:
                    url: jdbc:${DATASOURCE_DBTYPE:mysql}://${DATASOURCE_HOST:chauncy}:${DATASOURCE_PORT:3358}/tickets?characterEncoding=UTF-8&useUnicode=true&useSSL=false
                    username: ${DATASOURCE_USERNAME:root}
                    password: ${DATASOURCE_PASSWORD:root}
                    driver-class-name: com.mysql.cj.jdbc.Driver # 3.2.0开始支持SPI可省略此配置
                slave1:
                    driver-class-name: com.mysql.jdbc.Driver
                    url: jdbc:${DATASOURCE_DBTYPE:mysql}://${DATASOURCE_HOST:vanchan}:${DATASOURCE_PORT:13358}/tickets?characterEncoding=UTF-8&useUnicode=true&useSSL=false
                    username: ${DATASOURCE_USERNAME:root}
                    password: ${DATASOURCE_PASSWORD:root}
    cloud:
        compatibility-verifier:
            enabled: false
logging:
    level:
        com.springboot: debug
        java.sql.PreparedStatement: debug
        com.baomidou: debug

springdoc:
    api-docs:
        enabled: true
    swagger-ui:
        path: /swagger
mybatis-plus:
    typeEnumsPackage: com.baomidou.mybatisplus.test.web.enums
    configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
