spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:${DATASOURCE_DBTYPE:mysql}://${DATASOURCE_HOST:chauncy}:${DATASOURCE_PORT:3358}/tickets?characterEncoding=UTF-8&useUnicode=true&useSSL=false
        username: ${DATASOURCE_USERNAME:root}
        password: ${DATASOURCE_PASSWORD:root}
        names: odps
        odps:
            type: com.alibaba.druid.pool.DruidDataSource
            driver-class-name: com.aliyun.odps.jdbc.OdpsDriver
            url: jdbc:odps:XX/api?project=vanchan
            username: XX
            password: XX

    cloud:
        compatibility-verifier:
            enabled: false
logging:
    level:
        com.springboot: debug
        java.sql.PreparedStatement: debug
        com.baomidou: debug

springdoc:
    api-docs:
        enabled: true
    swagger-ui:
        path: /swagger
mybatis-plus:
    typeEnumsPackage: com.baomidou.mybatisplus.test.web.enums
